XXX Setting viaIR: true causes a test failure
  0 passing (999ms)
  1 failing

  1) Edition
       purchases a edition:
     AssertionError: Expected transaction to be reverted with Not for sale, but other exception was thrown: Error: Transaction reverted: function was called with incorrect parameters